### ISSUE TITLE
Bug: Two Cursors on word!

### ISSUE THREAD

**Issue by yashchaudhari008** [FurqanAnwar/Typing-Simulator#11]
When cursor is at the end of word, and we press any wrong key(other than space & correct letter key) we get two cursors!

![image](https://user-images.githubusercontent.com/29065088/135964048-8b43e908-1578-4751-83cb-601d62075345.png)

**Comment by FurqanAnwar** [comment]
Thanks for reporting this bug, I on it right now

**Comment by yashchaudhari008** [comment]
Assign me, am almost done with it! 👍🏼

**Comment by FurqanAnwar** [comment]
The issue has been resolved, there were some issue with your PR I've commented those issue out. Check out the following link for more information https://github.com/FurqanAnwar/Typing-Simulator/pull/15
