### ISSUE TITLE
Bug: User can skip words by pressing spacebar. 

### ISSUE THREAD

**Issue by yashchaudhari008** [FurqanAnwar/Typing-Simulator#7]
### When user complete one word and switch to other; just in time between them, if player press SPACEBAR key rapidly he can skip words!
![2021-10-04_21-33-27_Trim](https://user-images.githubusercontent.com/29065088/135885741-2ff0bebf-a642-4b44-8241-464f7f8b2fef.gif)
.

**Comment by FurqanAnwar** [comment]
Ok, I'll have a look at it. If you got any fix let me know

**Comment by FurqanAnwar** [comment]
This issue is being fixed in this commit 
https://github.com/FurqanAnwar/Typing-Simulator/commit/1ae7b2fc6003c1d3c0765ecc4008fc9f44881511
